name: CI

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Check out Git repository
      uses: actions/checkout@v2
    
    - name: Snapcraft
      uses: snapcore/action-build@v1
      with:
        snapcraft-args: --enable-experimental-extensions

    - uses: actions/upload-artifact@v2
      with:
        name: elementaryos-code_6.0.1_amd64.snap
        path: elementaryos-code_6.0.1_amd64.snap
